allowBuilds:
  core-js: false
  esbuild: true
minimumReleaseAgeExclude:
  - '@interop/did-method-webvh@3.5.1'
  - '@interop/ezcap@7.3.0'
  - '@interop/verifier-core@3.3.0'
  - '@interop/did-io@4.0.6'
